title: Scaffold
tagline: A minimalist yet powerful Jekyll theme for bloggers
author:
  name: Songzi Vong
  url: https://twitter.com/sziv2p/
  avatar: https://avatars.githubusercontent.com/u/72621374
paginate: 10
tags_path: /tags/

exclude:
  - jekyll-theme-scaffold.gemspec
  - LICENSE.txt
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
